CREATE TABLE currency (
    currency_id INT PRIMARY KEY AUTO_INCREMENT,
    code CHAR(3) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(10),
    country VARCHAR(100),
    amount DECIMAL(18, 4) NOT NULL DEFAULT 0  
);

-- INSERT VALUES AS WELL
INSERT INTO currency (code, name, symbol, country, amount) VALUES
('USD', 'United States Dollar', '$', 'United States', 1.0000),
('EUR', 'Euro', '€', 'European Union', 0.91),
('JPY', 'Japanese Yen', '¥', 'Japan', 144.50),
('GBP', 'British Pound Sterling', '£', 'United Kingdom', 0.80),
('AUD', 'Australian Dollar', '$', 'Australia', 1.45),
('CAD', 'Canadian Dollar', '$', 'Canada', 1.35),
('CHF', 'Swiss Franc', 'CHF', 'Switzerland', 0.91),
('CNY', 'Chinese Yuan', '¥', 'China', 7.30),
('SEK', 'Swedish Krona', 'kr', 'Sweden', 10.55),
('NZD', 'New Zealand Dollar', '$', 'New Zealand', 1.59),

('MXN', 'Mexican Peso', '$', 'Mexico', 17.40),
('SGD', 'Singapore Dollar', '$', 'Singapore', 1.35),
('HKD', 'Hong Kong Dollar', '$', 'Hong Kong', 7.82),
('NOK', 'Norwegian Krone', 'kr', 'Norway', 11.00),
('KRW', 'South Korean Won', '₩', 'South Korea', 1332.00),
('TRY', 'Turkish Lira', '₺', 'Turkey', 26.50),
('RUB', 'Russian Ruble', '₽', 'Russia', 90.00),
('INR', 'Indian Rupee', '₹', 'India', 82.20),
('BRL', 'Brazilian Real', 'R$', 'Brazil', 4.80),
('ZAR', 'South African Rand', 'R', 'South Africa', 19.30),

('DKK', 'Danish Krone', 'kr', 'Denmark', 6.80),
('PLN', 'Polish Zloty', 'zł', 'Poland', 4.25),
('TWD', 'New Taiwan Dollar', '$', 'Taiwan', 30.50),
('THB', 'Thai Baht', '฿', 'Thailand', 35.70),
('MYR', 'Malaysian Ringgit', 'RM', 'Malaysia', 4.80),
('IDR', 'Indonesian Rupiah', 'Rp', 'Indonesia', 15000.00),
('CZK', 'Czech Koruna', 'Kč', 'Czech Republic', 20.90),
('ILS', 'Israeli New Shekel', '₪', 'Israel', 3.60),
('CLP', 'Chilean Peso', '$', 'Chile', 820.00),
('PHP', 'Philippine Peso', '₱', 'Philippines', 56.50),

('AED', 'United Arab Emirates Dirham', 'د.إ', 'United Arab Emirates', 3.67),
('COP', 'Colombian Peso', '$', 'Colombia', 4700.00),
('SAR', 'Saudi Riyal', 'ر.س', 'Saudi Arabia', 3.75),
('RON', 'Romanian Leu', 'lei', 'Romania', 4.50),
('NGN', 'Nigerian Naira', '₦', 'Nigeria', 460.00),
('PKR', 'Pakistani Rupee', '₨', 'Pakistan', 290.00),
('VND', 'Vietnamese Dong', '₫', 'Vietnam', 24000.00),
('EGP', 'Egyptian Pound', '£', 'Egypt', 30.90),
('BDT', 'Bangladeshi Taka', '৳', 'Bangladesh', 109.00),
('KWD', 'Kuwaiti Dinar', 'د.ك', 'Kuwait', 0.31),

('QAR', 'Qatari Riyal', 'ر.ق', 'Qatar', 3.64),
('KZT', 'Kazakhstani Tenge', '₸', 'Kazakhstan', 470.00),
('UAH', 'Ukrainian Hryvnia', '₴', 'Ukraine', 36.80),
('DOP', 'Dominican Peso', 'RD$', 'Dominican Republic', 55.00),
('CRC', 'Costa Rican Colon', '₡', 'Costa Rica', 565.00),
('PEN', 'Peruvian Sol', 'S/', 'Peru', 3.90),
('LKR', 'Sri Lankan Rupee', 'Rs', 'Sri Lanka', 321.00),
('OMR', 'Omani Rial', 'ر.ع.', 'Oman', 0.38),
('MAD', 'Moroccan Dirham', 'د.م.', 'Morocco', 10.25),
('JMD', 'Jamaican Dollar', 'J$', 'Jamaica', 155.00),

('AZN', 'Azerbaijani Manat', '₼', 'Azerbaijan', 1.70),
('BGN', 'Bulgarian Lev', 'лв', 'Bulgaria', 1.79),
('HRK', 'Croatian Kuna', 'kn', 'Croatia', 6.90),
('HUF', 'Hungarian Forint', 'Ft', 'Hungary', 370.00),
('ISK', 'Icelandic Krona', 'kr', 'Iceland', 130.00),
('MXV', 'Mexican Unidad de Inversion (UDI)', 'MXV', 'Mexico', 17.60),
('NAD', 'Namibian Dollar', '$', 'Namibia', 19.30),
('TZS', 'Tanzanian Shilling', 'Sh', 'Tanzania', 2400.00),
('UGX', 'Ugandan Shilling', 'Sh', 'Uganda', 3800.00),
('XAF', 'Central African CFA Franc', 'FCFA', 'Central African States', 600.00);
